### PR TITLE
Getting there... 7 non-passing functional tests left

### PR DESCRIPTION
**Pull request by ngzax**

### CODE REVIEW

**Comment by ggordon** [comment]
pulled into master, check out my develop branch, it is ported to rails3, all tests pass

**Comment by ngzax** [comment]
awesome, thanks.  I wonder what I am missing, though? Did you have to change anything to get them to pass?  Maybe I'm just missing a gem or something?

**Comment by ggordon** [comment]
yes, probably a missing gem, i think i saw you commented out mocha, it's needed. what are the errors?

**Comment by ngzax** [comment]
I'll have to look deeper.  I put mocha back in but still have 7 failures.  I think there's a problem with permalink too.

**Pull request merged**
